### ISSUE TITLE
Notify activity authors

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#149]
In #109, @patricialoeblein pointed out:

> There are  only  6 Energy Skate Park Basics activities (1 and 2 are Gold star). I listed them below. There are however, over 30 authors for Energy Skate Park.  I am wondering if the new bouncing is only for the html5 sims and are we wanting only teachers who have contributed activities to be queried? Lots of people use the sim, but have not posted activities. I wonder whom to request testing and reflecting?
Teaching Ideas for Energy Ckate Park Basics: 
Title	 Authors	 Level	 Type	 Updated
1.Energy Skate Park Basics Lesson  UTeach Middle School PhET Team	MS	Lab	6/22/12
2.Energy Skate Park Basics 	Noah PodolefskyMS	Lab	2/21/12
3.Energy Skate Park Basics Energy Exploration	Jessica Colonel	MS	Lab	3/21/13
4.Conservation of Energy - conceptual	Paul Broberg	MS/HS	Lab	4/17/12
5.Conservation of Energy (basic) PhET Lab	Chris Bires	HS/MS	Lab	4/7/12
6. Introduction to Energy Model	Greg Schade	HS/MS	Lab	2/21/12

We should make an effort to notify authors when we publish the new version.

**Comment by ariel-phet** [comment]
Issue no longer seems relevant, closing
