### ISSUE TITLE
The sim really stutters when the mouse changes from hand to arrow and back

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#208]
Win8/Chrome, The sim really stutters when the mouse changes from hand to and back

**Comment by jessegreenberg** [comment]
I am not seeing this happen at all, though I only have access to Windows 10. The general issue https://github.com/phetsims/scenery/issues/275 has been closed because starting May 2015 developers  began to report that this is no longer an issue. @samreid can this issue be closed?

**Comment by samreid** [comment]
Yes, thanks!  Closing.
