### ISSUE TITLE
Undesired ability to push parts of track off the screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/energy-skate-park-basics#271]
To reproduce:
1. Take out a track on the 3rd screen
2. Finger A down on a control point
3. Finger B down on the track's segment (not on a point)
4. Move finger A to the ground and wiggle around vertically, while wiggling finger B (technical terms!)
The other control points (and rest of the track) move up off-screen, increasing the size of the track.

Video: http://phet.colorado.edu/files/tmp/20140926_232610.mp4 (~1 MB)

Code Review: https://github.com/phetsims/energy-skate-park-basics/issues/221

**Comment by megan-phet** [comment]
@jessegreenberg it's fixed in master.

**Comment by megan-phet** [comment]
@jessegreenberg it's fixed on master.

**Comment by jessegreenberg** [comment]
This is fixed in master, closing.
