### ISSUE TITLE
Bar chart goes behind skater but in front of track

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#295]
Discovered during #294: In order to use a dedicated WebGL Layer and avoid moveToFront calls which caused flickering and the creation of multiple canvases, we have a situation where the track goes in between the bar chart background and the bars like so:

![image](https://cloud.githubusercontent.com/assets/679486/4565745/b251914a-4f22-11e4-834e-a9438ad3cec4.png)

I recommend that we leave this problem as it is for 1.0, and worry about it once we have broader webgl support.  Note: this only occurs on the Playground screen, and only if a screen goes to the left of the energy bar chart and the energy bar chart is open, and the track is down in the bar region.

**Comment by jessegreenberg** [comment]
This was recently reported again in https://github.com/phetsims/energy-skate-park-basics/issues/295. I added the `EnergySkateParkBasicsView.trackLayer` in front of the `barGraphForeGround` and `barGraphBackGround` and the sim seemed to behave OK in Chrome, I didn't see any flickering. @samreid how can I test this to see if  we still  need to layer in this way?

**Comment by samreid** [comment]
If I recall correctly, one of the implementation constraints was for all of the WebGL layers to be adjacent, so that scenery could collapse them into a single canvas.  This allowed us to stay within memory constraints for iPad2.

**Comment by jessegreenberg** [comment]
Thanks @samreid, then Ill revert the change. I would guess based on prioritization of this issue that this may be deferred for the upcomming Lol/phetio release, and maybe we could look into it as part of energy-skate-park. @ariel-phet can you please confirm?

**Comment by ariel-phet** [comment]
@jessegreenberg yes, this can be deferred and looked into as part of ESP

**Comment by jessegreenberg** [comment]
This is no longer the behavior now that WebGL is being removed from the sim in https://github.com/phetsims/energy-skate-park/issues/66 and the layering requirements to support WebGL are no longer necessary.
