### ISSUE TITLE
iPad lag when moving track node

### ISSUE THREAD

**Issue by bryo5363** [phetsims/energy-skate-park-basics#299]
The iPad has a pretty severe lag when moving a track point node. The sim will freeze up and will resume 2-3 seconds after moving the node. 

EDIT: @samreid thinks @bryo5363 was testing this version: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.0.0-dev.76/energy-skate-park-basics_en.html

**Comment by jessegreenberg** [comment]
Testing the sim on an iPad Air 2 (which is currently our platform of lowest performance) and I am not seeing any of the issues reported here. The skater continues to move smoothly while track and control points are dragged. I don't see any freezing or slowdown. So closing this issue.
