### ISSUE TITLE
WebGL does not work for Safari 7.0.5 (9537.77.4)

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/energy-skate-park-basics#304]
For the link  http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.0.0-rc.16/energy-skate-park-basics_en.html?en 
black lines are still present within the pie chart.

Troubleshooting information (do not edit):
Name: Energy Skate Park: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.0.0-rc.16/energy-skate-park-basics_en.html?en
Version: 1.0.0-rc.16
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4
Language: en-us
Window: 1280x653
Pixel Ratio: 1/1
WebGL: disabled

**Comment by samreid** [comment]
We no longer support Mobile Safari 7, closing.
