### ISSUE TITLE
Restore WebGL support for new scenery

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#313]
When scenery ohtwo became master today, it didn't support Energy Skate Park's way of doing webgl.  So ESPB should be updated to use webgl (once scenery supports it properly.)

For the moment I've turned off WebGL support so the sim will still run on every device, see 774f0fa819d700590c54140cec7e91d58b62ecae

**Comment by samreid** [comment]
This should be much easier now that @jonathanolson has added image support into webgl.

**Comment by samreid** [comment]
This will be critical to implement before Summer 2015 redeploy.

**Comment by samreid** [comment]
Actually, this could be more work than I expected.  Only the skater is an image--the bar chart, pie chart and speedometer needle are shapes.  Though perhaps the speedometer needle could be turned into an image.  We could use WebGLNode for the charts.

**Comment by jonathanolson** [comment]
I recall the pie chart being more custom than just a shape - did we drop that in order to work with Scenery 0.1's WebGL support?

**Comment by samreid** [comment]
Each pie slice is a triangle fan.  When we moved from scenery 0.1 to scenery 0.2, I manually overrode WebGL support to false until we could bring back support.

**Comment by samreid** [comment]
We decided to postpone work on this until other redeployments have started, then we can see how far scenery WebGL has come.

**Comment by samreid** [comment]
I tested on my iPad3 to see if the problems using SVG have disappeared with iOS updates.  The problems are still here, and we will still need WebGL for this motion to look smooth, consistent and non-stuttery on iPad.

Rough estimates for upgrading this:

| Time Estimate  | Work Item |
| ------------- | ------------- |
| 2 hours  | Rendering Skater in WebGL using scenery WebGL Image support (2 directions + container node and red dot are the complications, longer if scenery WebGL images conflict with WebGLNode at all, or 4-6 hours if we have to switch to WebGLNode for this)  |
| 4 hours  | Rendering Speedometer Needle in WebGLNode, without rendering anything else from the gauge in WebGL, which means configuring the gauge to not show its needle and to show a separate one in the webgl layer  |
| 8 hours  | Rendering the bar chart in WebGLNode, some of the code from scenery 0.1 support will be reusable, but it will not be a trivial port  |
| 8 hours  | Rendering the pie chart in WebGLNode, some of the code from scenery 0.1 support will be reusable, but it will not be a trivial port  |
| 2 hours  | Testing on several platforms after all of the above has been converted to WebGL and addressing any issues that come up  |

Total estimate: 24 hours (everything is +/- 30% or so)

**Comment by samreid** [comment]
@jessegreenberg volunteered to help out on this, we'll try to set up a time today.

**Comment by samreid** [comment]
@jonathanolson said he could also help out.

**Comment by samreid** [comment]
It seems like scenery webgl is not rendering toCanvasNodeSynchronous at the moment, https://github.com/phetsims/scenery/issues/519

**Comment by samreid** [comment]
There is a red dot under the skater that is using toCanvasNodeSynchronous, currently missing but hopefully the scenery fix will fix it as well.

**Comment by samreid** [comment]
@jonathanolson and I got most things working, we are still pending fixes for toCanvasNodeSynchronous and scenery support for WebGL rectangles for the remaining components.

**Comment by samreid** [comment]
WebGL support is restored, iPad3 performance levels are back to normal, closing.
