### ISSUE TITLE
important UI elements are drawn outside the layout bounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#316]
This is with master on all platforms. See screenshot below, with 'dev' query parameter.

![screenshot_453](https://cloud.githubusercontent.com/assets/3046552/6156266/d7c138be-b1f5-11e4-8d50-94e7408b63be.png)

**Comment by samreid** [comment]
A design decision was made for this sim that it would move control panels a bit further to the side when space is available.  When the screen is thin, it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/6159408/539f4f72-b212-11e4-8d60-4593729db6b5.png)

No controls get outside of the visible bounds.  Want to discuss further?

**Comment by pixelzoom** [comment]
OK. Didn't expect this behavior and (unfortunately) was using this sim to demonstrate PhET layoutBounds conventions to an intern.

Closing.
