### ISSUE TITLE
sim title on HTML category page is incorrect

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#318]
See screenshot below.  The title shown is "Energy Skate Park Basic", missing colon before "Basics". The title looks correct in the sim's package.json and strings file, so I'm guessing this is a website error.

![screenshot_484](https://cloud.githubusercontent.com/assets/3046552/6585502/ec5e8a36-c737-11e4-8f3e-f46bb9aee16e.png)

**Comment by aaronsamuel137** [comment]
I've pushed a change with the new title to the website repo. It'll be live on the next deploy.

**Comment by aaronsamuel137** [comment]
This was live awhile ago. Closing
