### ISSUE TITLE
energy-skate-park-basics fails lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#321]
% grunt lint
Building energy-skate-park-basics
/Users/cmalley/PhET/GitHub/energy-skate-park-basics
Running "jshint:repoFiles" (jshint) task
Linting js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js ...ERROR
[L174:C18] W078: Setter is defined without getter.
        set value( arrayOfArrayOfVector ) {

Warning: Task "jshint:repoFiles" failed. Use --force to continue.

Aborted due to warnings.
%

**Comment by samreid** [comment]
Fixed, closing.
