### ISSUE TITLE
Issue "?stringTest=double" covering "Normal" & "Slow Motion" options

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/energy-skate-park-basics#323]
Testing for Task https://github.com/phetsims/tasks/issues/245
The ramp pieces in the Playground mode covers the "Normal" & "Slow Motion" options
![screen shot 2015-05-26 at 12 03 22 pm](https://cloud.githubusercontent.com/assets/5631059/7819561/cdf7c6b2-039f-11e5-9367-e35b444e02ab.png)

**Comment by jessegreenberg** [comment]
Just observed this while reviewing phetsims/joist#141.

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/energy-skate-park-basics/issues/328, closing
