### ISSUE TITLE
bad URL for documentation of analytical model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#326]
EnergySkateParkBasicsModel.js contains this doc:

> For an analytical model, see http:// digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1387&context=phy_fac

This URL goes nowhere. Typo? Stale?

**Comment by samreid** [comment]
Somehow a whitespace sneaked in.  I fixed it, tested it and it seems good.  Closing.
