### ISSUE TITLE
Issue ?stringTest=X slider slightly shifts icons above

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/energy-skate-park-basics#329]
Testing for task phetsims/tasks#245

I noticed that the icons above the slider slightly shift either right or left when moving the slider to its min and max. The icons only move a few pixels.
Slider at default position 
<img width="200" alt="screen shot 2015-07-14 at 11 37 30 am" src="https://cloud.githubusercontent.com/assets/5631059/8680219/1cb958a8-2a1d-11e5-97a0-27e33655a684.png">

Slider at minimum
The icons have shifted slightly to the left
<img width="182" alt="screen shot 2015-07-14 at 11 37 38 am" src="https://cloud.githubusercontent.com/assets/5631059/8680225/22193110-2a1d-11e5-9c07-af0c1d28e849.png">

Slider at maximum 
The icons have shifted slightly to the right
<img width="184" alt="screen shot 2015-07-14 at 11 37 46 am" src="https://cloud.githubusercontent.com/assets/5631059/8680229/27ac1660-2a1d-11e5-961e-2f81ec420ec9.png">

**Comment by samreid** [comment]
Fixed above, closing.
