### ISSUE TITLE
User suggestion: replace double U with loop

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park-basics#330]
Suggestion received from user via phethelp:

One more comment from a user... The "Double U" shaped track has always bothered me because the skater looks like it's moving extremely fast around the top of the middle hump. This makes it hard for kids to notice that the skater's actually moving slower when higher up. I've used the "loop" in the past, but that's missing from the html5 version. Any chance of replacing the double U with a loop? Just a suggestion...

**Comment by ariel-phet** [comment]
@oliver-phet we have no plans of replacing the double U. The loop is something almost every kid builds on their own in an interview. If this user want to use a loop, please suggest that they simply build one on the playground screen.

**Comment by oliver-phet** [comment]
Email to user sent.
