### ISSUE TITLE
Long, Double string tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/energy-skate-park-basics#334]
Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.111 

Problem description: Long and Double string tests produce some overlap

Steps to reproduce: Perform string tests

Severity:

Screenshots:
Long:
![screen shot 2016-01-20 at 3 31 15 pm](https://cloud.githubusercontent.com/assets/12610678/12465546/cb900710-bf8b-11e5-935f-220af1692209.jpg)

Double:
![screen shot 2016-01-20 at 3 35 19 pm](https://cloud.githubusercontent.com/assets/12610678/12465554/d3931b5a-bf8b-11e5-8f70-af3f8f2f9778.jpg)

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: http://phettest.colorado.edu/energy-skate-park-basics/energy-skate-park-basics_en.html?ea&brand=phet
Version: 1.0.0 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1275x654
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
@ariel-phet said:

> Do you think you could get ESPB ready to go for redeploy by early next week? It seems that if only the i18n issues are fixed this should not be a major burden, is that correct?

Assigning myself for investigation.

**Comment by samreid** [comment]
For reference, the S2015R redeploy issue is here: https://github.com/phetsims/tasks/issues/476

**Comment by samreid** [comment]
I noticed there are several i18n issues and this is not a "parent" issue, I'll move my comments elsewhere.

**Comment by samreid** [comment]
The double test issue is noted here: https://github.com/phetsims/energy-skate-park-basics/issues/328

**Comment by samreid** [comment]
string test = double seems good for the most part after recent changes, string test = long doesn't reveal any fundamental issues, just long strings that need to be trimmed, closing.
