### ISSUE TITLE
Consider "Show Values" option to better align with NGSS

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/energy-skate-park-basics#335]
As I review the NGSS MS energy standards, these go to quantitative relationship - e.g. gathering evidence for linear relations or as square of velocity. At the moment, its challenging to gather this type of evidence with the sim. The qualitative emphasis is best start, but a values check box or a values screen could really enable more extensive NGSS-aligned lessons.

**Comment by arouinfar** [comment]
I think this is a great idea! I often use this simulation in workshops, and I've had one or two participants comment on the lack of quantitative data in this sim. Given that the full Energy Skate Park is not going to be ported in the near future, I think this would be a feature worth adding when this sim is redeployed.

**Comment by jessegreenberg** [comment]
@arouinfar can you please comment on this issue and whether this has been addressed in Energy Skate Park?

**Comment by arouinfar** [comment]
I think quantitative learning goals are best addressed by energy-skate-park. The Measure screen, in particular, could be used to address the learning goals mentioned by @kathy-phet. I think we can go ahead and close this issue @jessegreenberg.
