### ISSUE TITLE
Redeploy with i18n for S2015R

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#336]
@ariel-phet said:

> Do you think you could get ESPB ready to go for redeploy by early next week? It seems that if only the i18n issues are fixed this should not be a major burden, is that correct?

Assigning myself for investigation.

**Comment by samreid** [comment]
For reference, the S2015R redeploy issue is here: phetsims/tasks#476

**Comment by samreid** [comment]
The main requirement for redeploying Energy Skate Park: Basics will be restoring WebGL support: https://github.com/phetsims/energy-skate-park-basics/issues/313

This simulation was published as 1.0.0 using and old and incompatible WebGL implementation from Scenery 0.1.  When scenery moved to 0.2, the WebGL API changed significantly and Energy Skate Park: Basics has not yet been updated to use the scenery 0.2 WebGL API.

I provided time estimates in this comment for updating to WebGL:
https://github.com/phetsims/energy-skate-park-basics/issues/313#issuecomment-187519817

The bottom line is an estimate of 24 hours +/- 30% or so to update all 4 parts of the simulation that require WebGL (includes cross-platform developer testing).

Beyond this, it looks like some 4 hours of work or so to address the i18n issues. (Maybe a bit faster if things go smoothly).

> Do you think you could get ESPB ready to go for redeploy by early next week? It seems that if only the i18n issues are fixed this should not be a major burden, is that correct?

Together the estimate is 28 hours or so before a release candidate could be ready.  For me to get this done by early next week, I would need to postpone some PhET-iO work and the start date for CCK: Black Box, please advise.

**Comment by ariel-phet** [comment]
@samreid marking for status meeting and reassigning to you to bring up then. This work needs to proceed so it will be up to @kathy-phet as to what to push back.

**Comment by samreid** [comment]
Also to do: dealing with Edge canvas, will need a pointer from @jonathanolson in https://github.com/phetsims/energy-skate-park-basics/issues/338

**Comment by kathy-phet** [comment]
I am wondering if @jonathanolson might be able to pick up the ESPB GPL work, to keep Sam's time on PhET-iO and CCK: Black Box?

**Comment by ariel-phet** [comment]
@kathy-phet I sent you an email, where time should go in this case is a discussion for offline

**Comment by samreid** [comment]
There are two issues remaining before this is ready for publication, identified in #313 and #337, putting on hold until discussing prioritization with @kathy-phet at status meeting and until the dependent issues are closed.

**Comment by samreid** [comment]
At today's meeting I described that the remaining work for me (before RC) is minimal, and @kathy-phet requested for me to continue this work while starting up CCK.

**Comment by samreid** [comment]
On hold while #337 is reviewed by @ariel-phet.

**Comment by samreid** [comment]
Next steps:

1. Add more control points #339 
2. Use SHAs from Wave on a String
3. Developer testing
4. Dev testing
5. RC Testing
6. Publishing

**Comment by samreid** [comment]
@jonathanolson said we need to talk to him about file:// protocol issues in the WOAS SHAs.

**Comment by samreid** [comment]
This issue is on hold while awaiting @ariel-phet testing in #339

**Comment by samreid** [comment]
On iPad3 with all graphs on, one parabola in the playground screen and running 1.0.0 from the website, I'm seeing 57fps.

Same scenario with master: 57fps as well, so this seems OK.

I'm still seeing intermittent hiccups in the performance of both versions though.

**Comment by samreid** [comment]
I tested on OS X Chrome and Firefox and no problems noted.  Let's do a Windows test next.

**Comment by samreid** [comment]
Oops I should probably be testing with the SHAs.  I'll do a SHA-based build next.

**Comment by samreid** [comment]
Likewise, I should create the dev test candidate from a branch so if dev testing goes smoothly we can continue with the same code in RC testing.

**Comment by samreid** [comment]
The SHAs to use are listed in the tail of https://github.com/phetsims/tasks/issues/476

**Comment by samreid** [comment]
Even if the SHAs at the tail of tasks#476 aren't 100% current, they should be good enough for continued testing.

**Comment by samreid** [comment]
I’m preparing Energy Skate Park: Basics for S2015R.  It is currently published on the website as 1.0.0.  What should the redeploy version be?

I’m guessing that i18n constitutes a minor bump, but am not sure of convention or precedent.

**Comment by samreid** [comment]
I asked over Skype:

I’m going to create a branch for use for a dev deploy, in case things go well we can guarantee minimal code changes before RC.  Any problems with this?

Can I use `grunt deploy-rc` to publish a dev release?

Trying it out....

**Comment by samreid** [comment]
Seems like it worked OK, I'll use this version for developer testing and if that goes well we can use the same version for dev testing (and if that goes well, we can use that same branch for an RC).

http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.1/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
I tested on OS X Chrome and OS X Firefox with ?webgl=true and ?webgl=false and ?stringTest=none and ?stringTest=double and didn't see any issues.

Spot tests on IE and Win/Firefox didn't reveal any trouble.

iPad3 test seems OK, except for one thing: the address bar says "1.0.0" even though the link is launched from "1.1.0-dev.1".  I confirmed this discrepancy in other browsers.  What is causing this discrepancy?

**Comment by samreid** [comment]
I can see the version was passed through to the build server like so:

```
version=1.1.0-dev.1
```

**Comment by samreid** [comment]
Is this the price I pay for trying to use build-server to build something that doesn't have a suffix of "rc" or suffixless?

It seems I should mark this for developer meeting to get this figured out before putting QA resources on it.

**Comment by samreid** [comment]
Ah indeed there is logic in build-server like so:

```js
    if ( option === 'rc' ) {

      // if deploying an rc version use the -rc.[number] suffix
      version = versionMatch[ 0 ];
    }
    else {

      // otherwise strip any suffix
      version = versionMatch[ 1 ];
    }
    winston.log( 'info', 'detecting version number: ' + version );
```

Still not sure how this turned into 1.0.0 showing up in the title bar but not the folder name...  Should we change the build-server so it can build dev versions as well?  I was trying to build something as similar to RC as possible.

**Comment by samreid** [comment]
@jonathanolson pointed out that it is likely I forgot to run the initial `grunt` command, and that it used shas from pre-existing dependencies.json.

**Comment by samreid** [comment]
OK I ran the grunt command and the files were overwritten with the correct ones:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.1/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
- [ ] os x safari
- [ ] os x chrome
- [ ] os x firefox
- [ ] ie
- [ ] iPad
- [ ] win/firefox

**Comment by samreid** [comment]
Developer spot testing revealed no problems, so I'll create a tasks issue for dev testing for this version.

**Comment by samreid** [comment]
On hold for testing in https://github.com/phetsims/tasks/issues/540

**Comment by samreid** [comment]
RC1 was requested for Monday.

**Comment by samreid** [comment]
I followed the rc creation instructions in https://github.com/phetsims/phet-info/blob/master/sim_deployment.md and created http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.1/

I manually diffed with dev.1 and verified the only changes are in build time, build version, babel sha, espb sha, etc, so this is ready for a RC matrix.

**Comment by samreid** [comment]
On hold until RC testing from https://github.com/phetsims/tasks/issues/550 is complete.

**Comment by samreid** [comment]
I've merged master into the 1.1 branch.  The other change we need to pick up is a scenery change in SpriteSheet.js, changing the dimension of the sprite sheet from 2048x2048 to 1024x1024.  Rather than get new scenery from master, we could just create a scenery branch with this isolated change.

**Comment by samreid** [comment]
I created a scenery branch named "energy-skate-park-basics-1.1" and committed the 1024x1024 sprite sheet, which fixes the iPad crashes.

**Comment by samreid** [comment]
Testing the new RC I see this error:

> Uncaught Error: WebGLNode needs initializeWebGLDrawable implemented
> Uncaught TypeError: Cannot read property 'removeDrawable' of null

**Comment by samreid** [comment]
In order to generate WebGL screenshots, Energy Skate Park: Basics needs the new scenery--it will not be compatible with the minimal scenery branch.  If I am getting the new scenery, I do not know whether I will need any other repos to be updated at the same time.

@jonathanolson can you please comment whether I can update scenery's SHA to master in isolation or whether it has upstream or downstream changes I must get at the same time.

OR

@ariel-phet let me know whether we should update all SHAs for the next RC.  This would mean better test coverage for recent changes in master and a better chance that all repos are in harmony for Energy Skate Park: Basics, but a higher risk that we will detect another blocking issue and hence require a 3rd RC for Energy Skate Park: Basics.

**Comment by jonathanolson** [comment]
There have been about a months' worth of changes, for which ~15 commits I haven't been involved with. It would probably be safe if you want to just bump Scenery forward and test it (check with @jessegreenberg too). If you're going this route, we'd also want to integrate the phet-app changes from https://github.com/phetsims/phet-app/issues/24 (brand, joist, phetcommon).

I'd probably just update to master on everything and test, but I'm not sure how much of an issue a 3rd RC would be.

**Comment by samreid** [comment]
@jonathanolson thanks for your feedback.  @ariel-phet does this plan sound OK to you?  "Update to master SHAs for all repos for Energy Skate Park: Basics RC.2?"

**Comment by jessegreenberg** [comment]
Since my name was tagged, my only recent commits to scenery are for VirtualCursor (https://github.com/phetsims/scenery/issues/538), which should not impact this sim or the redeploy.

**Comment by ariel-phet** [comment]
@samreid sounds like a good plan to me. This is a good sim to shake out recent changes anyhow.

**Comment by samreid** [comment]
I posted this to the Skype dev channel:

> Is master stable in all common repos?  Are there any in-progress changes being made that could destabilize?  We want new SHAs for Energy Skate Park: Basics.

**Comment by samreid** [comment]
@jessegreenberg @pixelzoom and @andrewadare reported no known destabilizing work, and @jonathanolson already signed off on Scenery.  I don't see any work from @jbphet on Joist (which we speculated about today), so I think we can take SHAs from master.

**Comment by samreid** [comment]
I published RC.2 here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.2/

I also noted the new SHAs in tasks#476, linked above.

Developer spot tests:
OS X Firefox: good
OS X Firefox ?stringTest=double: good
iPad3: good
Win8: IE11: good

I'll create a tasks issue for RC testing.

**Comment by samreid** [comment]
On hold while testing proceeds in tasks.

**Comment by samreid** [comment]
It looks like the RC testing discovered #345 and #346 as well as poor performance on a few platforms.

**Comment by samreid** [comment]
Two browsers on Win7 had poor performance, and the same browsers had good performance on Win8.  I'm somewhat curious whether those browsers rendered outlines for the pie chart or not, this would tell us whether webgl was working or not on those platforms (outline = no webgl available).  In either case I'd recommend to create a deferred issue for investigating Win7 performance and publish 1.1 on the website.  Thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
@samreid I did a side by side comparison of 1.1.0-rc.2 with the published version on FF on my Win 7 desktop, no difference in performance compared to published version. Yes, clearly everything goes faster on chrome, but nothing pedagogically damaging here.

Agreed. make a deferred issue for Win7 performance, and go ahead with publication.

**Comment by samreid** [comment]
A few layout changes warrant a new screenshot.

**Comment by samreid** [comment]
Brief spot tests under OS X Chrome and iPad3 Safari don't reveal any problems.

**Comment by samreid** [comment]
Manually diff'ing 1.1.0 vs 1.1.0-rc.2 I confirmed the only differences are in the expected values (version numbers, babel sha, esb sha, date, etc.)

**Comment by samreid** [comment]
Deployed on figaro, tested, closing.
