### ISSUE TITLE
Review stringTest=double

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#337]
@ariel-phet can you please double-check the stringTest=double (pictured below in the dev bounds) and let me know if you want to make any other changes before we proceed?

![image](https://cloud.githubusercontent.com/assets/679486/13243326/0b602160-d9bb-11e5-9cca-a8352546fb9c.png)

**Comment by ariel-phet** [comment]
Hey @samreid several changes actually:

- the "Speed" label on the speedometer should have a maximum width, the label should not overlap the tick marks
- Using stringTest=long I can see that all panels are growing in size, so...
 - Energy Bar chart should not exceed the width or height it is with stringTest=double, after that strings should shrink
 - The control panel needs to be given a max width, I would say it should certainly not grow any larger than the stringTest=double width

**Comment by samreid** [comment]
@jessegreenberg volunteered to help with the gauge text for Forces and Motion: Basics, I'm pointing him to this issue so he can test here too.

**Comment by samreid** [comment]
@jessegreenberg I'm going to look at setting maxWidth in the gauge title

**Comment by samreid** [comment]
Empirically I determined radius*1.3 to be a good fit:

![image](https://cloud.githubusercontent.com/assets/679486/13442489/b1366a8c-dfb9-11e5-859f-090977f87df0.png)

**Comment by samreid** [comment]
I set maxWidths based on rounding up for ?stringTest=double and now it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/13443166/24473ecc-dfbd-11e5-83bb-847b4339a695.png)

Will commit shortly.

**Comment by samreid** [comment]
Fixed above, @ariel-phet can you pull master and review the stringTests?

**Comment by ariel-phet** [comment]
All looks good, closing!

**Comment by phet-steele** [comment]
@ariel-phet @samreid are we ignoring that the energy bar chart extends into the ground?

**Comment by ariel-phet** [comment]
@phet-steele I don't think extending beyond the ground is a problem, but perhaps this should be revisited. I was mainly focused on horizontal widths before, but the bar chart should probably not violate the space where the eraser/extra track sits (especially because the trash button can be obscured)

@samreid can we sat the max vertical of the bar chart to be just above the top of the extra track toolbox panel?

**Comment by samreid** [comment]
Here is the "before" picture:

![image](https://cloud.githubusercontent.com/assets/679486/13974834/f7acb5f4-f074-11e5-8e93-7513e41e977b.png)

**Comment by samreid** [comment]
After changing maxWidth from 113 to 90:

![image](https://cloud.githubusercontent.com/assets/679486/13974849/335de474-f075-11e5-9a5f-4c6271d524f3.png)

**Comment by samreid** [comment]
@ariel-phet would you like to pull and verify in master?

**Comment by ariel-phet** [comment]
@samreid that looks good...but I have one other small tweak request.

For the the Friction slider there could be a bit more negative space between the tittle (Friction) and the labels none and Lots. For instance it looks a bit tight with ?stringTest=Double. It seems that mass slider has a the right negative space

![capture](https://cloud.githubusercontent.com/assets/4051174/13976944/1eee3880-f08a-11e5-9563-4e755e4d49c0.PNG)

**Comment by phet-steele** [comment]
@ariel-phet @samreid something about a longer string moves the text downward. A really long string:
![espbstrings](https://cloud.githubusercontent.com/assets/5863899/14000425/d0cc3788-f106-11e5-9cbc-3456ceca9499.PNG)

**Comment by samreid** [comment]
In the above commit I standardized the metrics between FrictionControl and MassSlider. 

screens=2&stringTest=double
![image](https://cloud.githubusercontent.com/assets/679486/14164792/0ccfb2d2-f6c0-11e5-8b8d-0df815727ca4.png)

screens=2&stringTest=long
![image](https://cloud.githubusercontent.com/assets/679486/14164800/1ab8d8ba-f6c0-11e5-8db2-d55ed1fad89b.png)

in the top picture, there is less spacing between Mass and the slider labels because that text hasn't hit its max length and been shrunk.

@ariel-phet and @phet-steele any other cases to consider?  Does this seem good?  You can test in-context in master.

**Comment by ariel-phet** [comment]
@samreid things look a bit off spacing wise to me in the default strings case, perhaps you and I could find a time to sit down and polish in person or over skype.

**Comment by samreid** [comment]
I'll be on campus a few more minutes if you want to take a look now.

**Comment by samreid** [comment]
@ariel-phet and I iterated and committed changes above, @ariel-phet said this is OK to close.
