### ISSUE TITLE
Changing number of track pieces available in playground screen?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/energy-skate-park-basics#339]
Hey @samreid quick question...

If we wanted to change the number of track pieces available in the playground screen would this be an easy change...for instance if we wanted 8 pieces available, I assume this would be a minor change to the code, but I do not know how much logic revolves around the piece limitation. We had some teacher feedback that suggested more than 4 pieces might be useful. Can you comment?

**Comment by samreid** [comment]
This would be an easy change to make, but I recall that one reason we limited the number of tracks was due to performance constraints (more tracks = more numerical computation in each frame)

**Comment by ariel-phet** [comment]
@kathy-phet requested we try out more pieces for the redeploy

The key is that students should be able to make a hill and a loop, probably means ~ 6 pieces

Lets try this change and set up a dev test.

**Comment by samreid** [comment]
Currently there are 12 control points which gives 4 3-point tracks.  With this number of control points I am able to easily make 2 hills and a loop:

![image](https://cloud.githubusercontent.com/assets/679486/13512050/a24de4da-e155-11e5-98b1-c560a3557546.png)

@ariel-phet please advise.

**Comment by samreid** [comment]
@kathy-phet suggested 2 more tracks, I advised that the performance will drop proportionately on iPad, and @ariel-phet tested out and recommend one more track, so I'll increase the max number of control points from 12 to 15.

**Comment by samreid** [comment]
Fixed above, @ariel-phet please pull and test.

**Comment by ariel-phet** [comment]
@samreid this seems good with quick testing, but could you check if this has a major effect on ipad2 performance? Looks fine on my laptop

**Comment by samreid** [comment]
The frame rate of a dropping skater 46fps is not significantly different when 4 or 5 3-segment tracks are out.  So I think this invalidates my argument for keeping it at 15 control points instead of 18.  Still 15 seems like enough for making many tracks, including hill + roller coaster tracks and doesn't get the screen too cluttered, so let's proceed with this.
