### ISSUE TITLE
Consider adding Gravity options to better align with NGSS

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park-basics#340]
A middle school teacher commented that she uses Energy Skate Park in lieu of ESPB because:

> The basics version does not allow you to switch locations to the moon, Jupiter, and space.  This is a big deal because:
> 
> NGSS's standard MS-PS2-4 states that students must "construct and present arguments using evidence to support the claim that gravitational interactions are attractive and depend on the masses of interacting objects."  Our 8th grade team has racked our brains and cannot find any other way to have students "discover" this learning objective aside from using the full java version of Energy Skate Park. Students experiment to determine how having the skaters on Jupiter and the moon affects gravitational potential energy. 
> 
> NGSS's standard MS-PS2-2 states "Plan an investigation to provide evidence that the change in an object's motion depends on the sum of the forces on the object and the mass of the object." This learning objective is reinforced when the students switch the skater's location to space.  If the skate was already moving, they see it continue in motion and not come back down like it would on Earth.  Then once they click on "return skater," students are used to the skater immediately traveling down their track while on Earth, but instead the skater will stay at rest until a force is applied.   

The two standards mentioned by the teacher could be addressed using other PhET sims (like Gravity Force Lab or FAMB). However, it would be nice if ESPB could also address these standards, as it would give teachers a bit more flexibility in using the sim. Given that a port of Energy Skate Park doesn't seem to be on the horizon, I think it would be worth considering having a few benchmark values for gravity such as 0, Moon, Earth, Jupiter (but no slider/tweaker to fine tune the value of g).

If we were to add a gravity selection menu, it should probably appear underneath the Friction slider on the Friction and Playground screens. The Friction screen doesn't currently have the room to spare, but we could squeeze in the Gravity menu if the scene selection buttons could be reduced to 75% of their original size. I think the scene selection buttons are still very clear and usable at this size.
![image](https://cloud.githubusercontent.com/assets/8419308/13404258/090b4a6e-ded6-11e5-8a93-29034acdb9d8.png)

I'm not sure how feasible this request is, but perhaps @samreid can comment on this issue.

**Comment by ariel-phet** [comment]
@samreid just note we certainly would not be doing this work for this current redeploy (and unclear whether we want to add this feature to the basics version or not)

**Comment by samreid** [comment]
It doesn't sound like too much work, probably half a day (2hrs for user interface, 2hrs for model), assigning to @ariel-phet for prioritization, scheduling and deciding whether it will be in the basics version or not.

**Comment by ariel-phet** [comment]
I actually think from the mockup above adding this feature to the friction screen would be a bit too much. And it terms of scaffolding it might be conflating a bit too many factors on that screen.

@arouinfar what do you think about putting gravity on the intro screen and on the playground screen, but leaving it off the friction screen?

Mind doing a quick mockup of those two if you agree?

**Comment by arouinfar** [comment]
Thanks @samreid!

@ariel-phet makes an excellent point. I think putting the gravity selection on the Intro and Playground screens is a good option. Here's what the gravity drop-down would look like on these screens.

![image](https://cloud.githubusercontent.com/assets/8419308/13475911/85e360c8-e082-11e5-87bb-56e27f2b8b73.png)

![image](https://cloud.githubusercontent.com/assets/8419308/13475891/6e9728b4-e082-11e5-84c8-dfbda0aecb5f.png)

Were you thinking something along these lines @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar yes, that is what I was thinking, we would need a bit more negative space vertically separating the word gravity, but otherwise that is definitely the idea!

**Comment by arouinfar** [comment]
Good catch @ariel-phet. I meant to adjust the negative space, but I left the spacing from the original mockup of the Friction screen. This feels a bit better to me.

![image](https://cloud.githubusercontent.com/assets/8419308/13479434/127675be-e094-11e5-87fe-bb3d30965389.png)

![image](https://cloud.githubusercontent.com/assets/8419308/13479445/1f96ad5e-e094-11e5-9a9d-e36730347955.png)

**Comment by samreid** [comment]
In Java we have different backgrounds for Mars, Earth, Space, Moon.  Are we doing different backgrounds for HTML5 too?

**Comment by arouinfar** [comment]
@samreid, yes I think we should have different backgrounds. Aside from being whimsical, it does provide some nice cueing and could allow teachers to more easily see what their students are working on. This would most likely be a task for a graphic artist.

**Comment by samreid** [comment]
Something to consider before requesting artwork: it must work at a variety of aspect ratios.

**Comment by ariel-phet** [comment]
Sounds like we will make this change, but it is deferred until a later date. Unassigning

**Comment by jessegreenberg** [comment]
We have gravity in energy-skate-park. @arouinfar can this be closed?

**Comment by arouinfar** [comment]
Yes, let's close
