### ISSUE TITLE
Where is the 1.0 branch?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#341]
While I was working on #336 I noticed that there is no 1.0 branch.  Where is it?  How has @jonathanolson been doing maintenance releases without it?

:question: :question: :question:

**Comment by jonathanolson** [comment]
Previous notes from https://github.com/phetsims/yotta/issues/17:
```
energy-skate-park-basics/1.0.0
HAS NO 1.0 BRANCH - Existed, see phetsims/energy-skate-park-basics#132, existed until at least Nov 10, 2014
Self commit exists, phetsims/energy-skate-park-basics@4220fb0
Dependencies.json (https://github.com/phetsims/energy-skate-park-basics/blob/4220fb0c2a11b2a2d5133fbf37df8ad8ab357240/dependencies.json)
Self looks slightly off, and self is DIFFERENT than deployed dependencies.json. Others look the same?
self: 4220fb0c2a11b2a2d5133fbf37df8ad8ab357240
phet: 1bfd46f1f42c6cb305ba70f281d195211bc4ac00
```

Manually patched with Hewlett change, and it has not received other translations (no non-translatable sims had everything in order where I could check out SHAs and build).

If you need to create the branch:
```sh
git checkout 4220fb0c2a11b2a2d5133fbf37df8ad8ab357240
git checkout -b 1.0
```

**Comment by jonathanolson** [comment]
Feel free to create it, should be fine.

**Comment by samreid** [comment]
I created the 1.0 branch.
