### ISSUE TITLE
WebGL not working for Firefox

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#342]
Test device:
Bates

Operating System:
Windows 7

Browser:
Firefox 45.0

Problem description:
Lines still show on the pie chart

Steps to reproduce:
enable pie chart

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/13714552/7eb03004-e78c-11e5-93f1-5763f9413633.png)

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.1/energy-skate-park-basics_en.html?webgl=true
Version: 1.1.0-dev.1 2016-03-10 05:05:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Language: en-US
Window: 1366x655
Pixel Ratio: 1/1
WebGL: disabled
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"2dfd7daf","branch":"HEAD"},"babel":{"sha":"ba586a78","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"662df961","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"energy-skate-park-basics":{"sha":"74761285","branch":"HEAD"},"joist":{"sha":"09590795","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"3984862d","branch":"HEAD"},"scenery-phet":{"sha":"5d9dafb2","branch":"HEAD"},"sherpa":{"sha":"fc4c2c96","branch":"HEAD"},"sun":{"sha":"3a0cabef","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

related to phetsims/tasks#540

**Comment by BryceAG** [comment]
also, it doesn't work without the ?webgl=true in the url either. I was seeing if for some reason it defaulted to be false for firefox.

**Comment by samreid** [comment]
From the debug information above:

```
WebGL: disabled
```

This means that Firefox on that computer does not know how to communication WebGL to the GPU, this is not something that necessarily needs to be solved, but may be solved by a future update to Firefox or updating Graphics Drivers.
