### ISSUE TITLE
Sim death with two node track

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park-basics#344]
On the "Playground" screen, dragging out a track and deleting a node results in a two node track. Placing the skater on this track and manipulating a node of the track kills the sim. Tested on Win 10 browsers and Mac OSX (Dirac, 10.11.4) browsers with the following, uglified, failed assertion:
```
Uncaught Error: not finite
n.correctEnergy @ energy-skate-park-basics_en.html:578
n.stepTrack @ energy-skate-park-basics_en.html:578
n.stepModel @ energy-skate-park-basics_en.html:578
n.step @ energy-skate-park-basics_en.html:578
i.stepSimulation @ energy-skate-park-basics_en.html:604
i.runAnimationLoop @ energy-skate-park-basics_en.html:604
```
I reproduced in requirejs + master (phettest) with a slightly different error and stack trace:
```
Uncaught Error: Assertion failed: undefined
window.assertions.assertFunction @ assert.js:23
inherit.stepEuler @ EnergySkateParkBasicsModel.js?bust=1459191614921:739
inherit.stepTrack @ EnergySkateParkBasicsModel.js?bust=1459191614921:854
inherit.stepModel @ EnergySkateParkBasicsModel.js?bust=1459191614921:1090
inherit.step @ EnergySkateParkBasicsModel.js?bust=1459191614921:370
inherit.stepSimulation @ Sim.js?bust=1459191614921:723
inherit.runAnimationLoop @ Sim.js?bust=1459191614921:661
```
This is what is seen (ignore slow performance):
![espb01](https://cloud.githubusercontent.com/assets/5863899/14087587/f62af1a6-f4e7-11e5-8f58-5fd4505187a3.gif)

For phetsims/tasks/issues/550.

Troubleshooting information:
Name: ‪Energy Skate Park: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.1/energy-skate-park-basics_en.html
Version: 1.1.0-rc.1 2016-03-18 03:00:21 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"2dfd7daf","branch":"HEAD"},"babel":{"sha":"f15f8275","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"662df961","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"energy-skate-park-basics":{"sha":"05144e76","branch":"HEAD"},"joist":{"sha":"09590795","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"3984862d","branch":"HEAD"},"scenery-phet":{"sha":"5d9dafb2","branch":"HEAD"},"sherpa":{"sha":"fc4c2c96","branch":"HEAD"},"sun":{"sha":"3a0cabef","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by samreid** [comment]
Proposed fix is above, @phet-steele can you verify this in master?

**Comment by phet-steele** [comment]
Fixed for me.

**Comment by samreid** [comment]
Thanks, closing.
