### ISSUE TITLE
?showPointerAreas causes skater to be invisible

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/energy-skate-park-basics#346]
Probably not a real problem, but I noticed that when using ?showPointerAreas, the skater is invisible (only in the Intro page), and there is only the small red dot. You can still click the area where the skater should be and drag. 
I didn't see this on other computers, and it doesn't do this when using the sim normally without showPointerAreas.

Tested on OSX 10.11.4, Chrome. 
Screenshot
![screen shot 2016-04-08 at 3 16 24 pm](https://cloud.githubusercontent.com/assets/11947677/14397828/fde49f2e-fd9c-11e5-9ac4-282b640f23c2.png)

**Comment by brroberts1231** [comment]
This happens on chrome only, fine on safari and firefox. Tested with &webgl=false, and the skater was visible, but then if you delete webgl=false and reload the page, she is visible for some reason.
When the skater is not visible, the needle on the speedometer is also not visible. 
Will test on 10.10.5 and 10.9.5.

**Comment by brroberts1231** [comment]
Still happens on 10.10.5 and 10.9.5, chrome only. 
phetsims/tasks#564

**Comment by samreid** [comment]
OS X 10.11.3 and Chrome Version 49.0.2623.110 (64-bit) doesn't show this problem.  Scenery points out that showing the pointer areas is somewhat demanding and I'm not too concerned about investigating this before release.

**Comment by jessegreenberg** [comment]
This is not an issue in Chrome Version 79.0.3945.88 (Official Build) (64-bit) on Win 10 or Chrome 78.0.3904.108 on macOS 10.15. I think this can be closed.
