### ISSUE TITLE
sims uses both GaugeNeedleNode and scenery-phet.GaugeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#348]
This sims uses both scenery-phet.GaugeNode and its own GaugeNeedleNode.  They appear to be almost identical, with GaugeNode now having diverged due to https://github.com/phetsims/scenery-phet/issues/233 and https://github.com/phetsims/scenery-phet/issues/201.

Delete GaugeNeedleNode and use scenery-phet.GaugeNode throughout.

**Comment by samreid** [comment]
Energy Skate Park: Basics splits the layers so that the needle, bars, pie chart and skater can be in the WebGL foreground.  The bar chart background, gauge node background, etc are in an SVG background.  What it seems we should do is factor out GaugeNeedleNode into a scenery-phet file, and have it be created by default in GaugeNode, with an option to skip creating it for cases like Energy Skate Park: Basics.

**Comment by samreid** [comment]
Or we could add options to hide/show the background/foreground.  Then ESPB could instantiate two GaugeNodes, one for the background and one for the foreground.  But this would take some finessing to make sure the foreground is webgl renderer compatible.

Also, these files aren't "almost identical".  Here is a diff of the top:

![image](https://cloud.githubusercontent.com/assets/679486/15797199/553c1ffc-29cd-11e6-9032-0bd11e0a7660.png)

And the bottom:
![image](https://cloud.githubusercontent.com/assets/679486/15797202/5f9d2630-29cd-11e6-86db-323a5fb02969.png)

They share about 30 lines in common, including this logic:
![image](https://cloud.githubusercontent.com/assets/679486/15797207/8686aba4-29cd-11e6-9e9b-9543fea5f5e5.png)

and these options:
![image](https://cloud.githubusercontent.com/assets/679486/15797209/8cbb6bfe-29cd-11e6-822f-401f7287a532.png)

In my opinion, this feature "show a needle that looks identical to the GaugeNode's needle but can be rendered in WebGL for Energy Skate Park: Basics" warrants this version, and I recommend to close the issue.  The Energy Skate Park: Basics needle exists for the life of the sim and doesn't need dispose.
