### ISSUE TITLE
Get rid of intermediate "energy-skate-park-basics" directory under js/

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#350]
Could be done during instrumentation https://github.com/phetsims/phet-io/issues/520

**Comment by samreid** [comment]
Actually, this intermediate directory may need to be kept.  I looked for a single-screen exemplar to see if there was a precedent and found example-sim.  It has this intermediate directory too.  I can't recall the reason for it, but perhaps we are supposed to keep it.  Can @jbphet @jonathanolson @pixelzoom @jessegreenberg or @andrewadare remind me why we have this intermediate directory?  I'll tag for developer-meeting but would be nice if someone could remind me before then.  I recall we had a conversation about this about a year ago (or more), but I just can't remember the details.

**Comment by pixelzoom** [comment]
We decided long ago to have a directory per screen, regardless of the number of screens. Besides the general advantage of consistency (single screen sim not a special case), the biggest advantage is probably realized if/when you need to add a screen to a single-screen sim.  Other examples include balloons-and-static-electricity, beaker, black-body-spectrum, curve-fitting, john-travoltage, wave-on-a-string,...

**Comment by samreid** [comment]
Sounds great, thanks @pixelzoom!
