### ISSUE TITLE
User reported issue: shifting of play area

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park-basics#354]
Test device:

Operating System: Mac os 10.11.6

Browser: Safari 9.1.2

Problem description: Shifting of animation/screen

Steps to reproduce: ran as html5 and directly from phET site

Severity: Sever shifting.  I am not at school so cannot try on chrombook.  

Screenshots: screenshots sent to Oliver

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html
Version: 1.1.2 2016-08-15 01:14:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7
Language: en-us
Window: 2319x1379
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 ATI-1.42.15)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"122a2c3d","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"chipper":{"sha":"97148ee1","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"energy-skate-park-basics":{"sha":"633ea7ef","branch":"HEAD"},"joist":{"sha":"1fad8aae","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"a29c912a","branch":"HEAD"},"scenery":{"sha":"7db0478c","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"2b2bdfd9","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}
<img width="2560" alt="screen shot 2016-08-18 at 11 04 58 am" src="https://cloud.githubusercontent.com/assets/5090275/17780132/8ae3e23a-6527-11e6-9fc0-d12a58eb685e.png">

**Comment by oliver-phet** [comment]
@phet-steele Can you see if you can reproduce on our closest testing mac?

**Comment by phet-steele** [comment]
@oliver-phet I cannot reproduce. The user has a decently high screen resolution (higher than mine), so I'll find a high resolution screen to try next.

**Comment by samreid** [comment]
Try with ?webgl=false and ?webgl=true to see if one of those cases triggers the problem.

**Comment by phet-steele** [comment]
> Try with ?webgl=false and ?webgl=true to see if one of those cases triggers the problem.

This did not cause the issue.

**Comment by oliver-phet** [comment]
Here's a second image with bar graphs also shifted.
<img width="2560" alt="screen shot 2016-08-18 at 10 45 26 am" src="https://cloud.githubusercontent.com/assets/5090275/17782789/67961efa-6532-11e6-8e40-0ddb8d515924.png">

**Comment by samreid** [comment]
As a workaround, you could report to the client that running with this `?webgl=false` link should solve the problem:
https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html?webgl=false

**Comment by oliver-phet** [comment]
Update from user:

> Yes!  This worked.  
> 
> What do I need to do?  That is, when I encounter the WebGL problem, how do I disable the webgl?  You gave me a link for this one, but what about other simulations?  Also, do I give students the link you just gave me to run the simulation?

**Comment by phet-steele** [comment]
@samreid @oliver-phet I could not reproduce on a high resolution screen, either.

**Comment by oliver-phet** [comment]
@samreid How would you recommend directing this user? Are we recommending users disable WebGL to run the sim?

**Comment by samreid** [comment]
> What do I need to do? That is, when I encounter the WebGL problem, how do I disable the webgl? You gave me a link for this one, but what about other simulations?

The WebGL rendering of any PhET simulation can be disabled by appending ?webgl=false to the URL.

> Also, do I give students the link you just gave me to run the simulation?

Yes, you can either put links on your classroom website that include the ?webgl=false, or direct them to the simulation link, then show them how to append ?webgl=false to the URL in the browser.  How many computers have you identified this problem on?

**Comment by ariel-phet** [comment]
@oliver-phet it would also be great if the user lets us know if they see this on ANY other platform, since it is the first known report of such an issue.

**Comment by samreid** [comment]
> Are we recommending users disable WebGL to run the sim?

Only users like this that have seen WebGL-specific bugs.

**Comment by phet-steele** [comment]
> lets us know if they see this on ANY other platform

We can wait to see what they say, but I didn't have any luck pinning this down.

**Comment by oliver-phet** [comment]
Haven't heard any updates from the user on this issue. Closing for now and will reopen if this comes up in the future.
