### ISSUE TITLE
Mike suggests including ability to change potential energy reference 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/energy-skate-park-basics#357]
@phetsims/dubson suggested that to meet the learning goals of his uses the "basics" sim has everything he needs except the ability to adjust the zero of potential energy.

We specifically left this ability out of the basics version since it seemed too advanced for a middle school sim, however, it is unclear when we will work on the port of the full Energy skate park (which includes graphs and the ability to change gravity and such). So it might be worth considering adding this feature (perhaps as a menu option, so more advanced users/teachers could turn on the functionality).

Seems like a good question for @kathy-phet 
marking for status meeting if she does not comment before then.

**Comment by ariel-phet** [comment]
Will visit this question next time we work on ESPB or ESP

**Comment by jessegreenberg** [comment]
We now have energy-skate-park which includes gravity and reference height line.
