### ISSUE TITLE
bars on bar graph can exceed size of bar graph for large mass skater 

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/energy-skate-park-basics#368]
Test device: Mac Airbook

Operating System: Sierra 10.12.4

Browser: Chrome Version 57.0.2987.133 (64-bit)

Problem description:
When dropping a large mass skater from a height nearly off the screen, the energy values exceed the size of the bar graph. 

Steps to reproduce:
1. Open sim (any of the options, all have the same issue)
2. click the bar graph option
3. change mass of skater to as large as possible
4. drag skater to top of screen  - notice total energy bar increases beyond the size of the bar graph as skater is dragged higher.  
5. Drop skater - notice bar graph appears as shown in screenshot below

Screenshots:
![screen shot 2017-04-22 at 8 05 27 am](https://cloud.githubusercontent.com/assets/17385784/25304474/fb2a2204-2735-11e7-8c51-de8158864750.png)

Related to: 
phetsims/tasks/issues/751

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.2.4-dev.3/energy-skate-park-basics_en.html
Version: 1.2.4-dev.3 2016-12-08 22:26:39 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1317x1041
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"1ea1df65","branch":"master"},"axon":{"sha":"b05e0921","branch":"master"},"babel":{"sha":"3a05632e","branch":"master"},"brand":{"sha":"41d9b92a","branch":"master"},"chipper":{"sha":"26adaea2","branch":"master"},"dot":{"sha":"56d026b6","branch":"master"},"energy-skate-park-basics":{"sha":"437228ac","branch":"master"},"joist":{"sha":"cd752b34","branch":"master"},"kite":{"sha":"e5affc4c","branch":"master"},"phet-core":{"sha":"87b5cab3","branch":"master"},"phetcommon":{"sha":"afb66c63","branch":"master"},"query-string-machine":{"sha":"b38c3c25","branch":"master"},"scenery":{"sha":"24b655a9","branch":"master"},"scenery-phet":{"sha":"2d3402d0","branch":"master"},"sherpa":{"sha":"727a3136","branch":"master"},"sun":{"sha":"e86f9f50","branch":"master"},"tandem":{"sha":"b161d61f","branch":"master"}}

**Comment by samreid** [comment]
@maggiewiseman thanks for this bug report.

I would like to note the problem is more extreme for thin aspect ratios, since the skater can go even higher.

![image](https://cloud.githubusercontent.com/assets/679486/25309306/f941150a-2786-11e7-835e-91035457bca2.png)

@ariel-phet would you like to change the scaling at all?  Shrinking the bars may make it more difficult to see values when the skater is closer to the ground, and I'm not sure that any students would get the wrong impression from having the bars go off the chart.  Another option would be to have the panel get bigger and smaller. (this would take longer to implement).

**Comment by ariel-phet** [comment]
@maggiewiseman thanks for the report.

@samreid in this particular case, I believe we made a design call that in extreme cases the bars would just leave the graph. Although somewhat aesthetically displeasing, there are no pedagogical consequences in my opinion
