### ISSUE TITLE
Sim needs retesting after PropertySet=>Property refactoring

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#371]
For https://github.com/phetsims/axon/issues/102 the simulation was rewritten to use Property instead of PropertySet.  This was not straightforward for the following reasons:

1. SkaterState uses object properties and Skater uses axon properties and there are methods that take {SkaterState|Skater}
2. Esoteric features such as PropertySet.addDerivedProperty, PropertySet.linkAttribute, etc
3. The sheer number of Properties and Emitters converted.

The commits are everything between
059e011c1153bbb6a260784f959f7cba7bf399cf
and
73f23826102fb02b12e2aab1b74bd8dd8a057feb

I've tested manually and run fuzz tests with assertions enabled and found (and solved) several lurking problems.  There may be others.  This sim should get some QA attention before being republished.  I recommend waiting until we want to publish another version from master in case other fixes like this are made between now and then (to avoid duplicating QA work), since the sim will likely need to be tested before next publication anyways.  Assigning @ariel-phet so he is aware of this issue.

**Comment by ariel-phet** [comment]
@samreid sounds good, unassigning for now

**Comment by jessegreenberg** [comment]
This is going to get tested in https://github.com/phetsims/QA/issues/134.

**Comment by jessegreenberg** [comment]
This is being tested and has been linked to the issue, removing my assignment.

**Comment by jessegreenberg** [comment]
energy-skate-park has gone through a few dev tests since this change, this can be closed.
