### ISSUE TITLE
skater teleports to joint

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#383]
For phetsims/QA#50

found on events: textarea for phet-io.

The skater keeps teleporting to the left joint in the playground section. The gif below starts with me restarting the skater to where it was. Sometimes this puts her on the track, sometimes on the ground. If it already puts her on the track then she teleports, or If i have to put her on the track manually she teleports anyway. It seems like the delay between placing her and her teleporting is slower when slow motion is toggled. Also (not shown) when she teleports a tiny bit of thermal energy is generated.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15327201/30757699-d86475f6-9f8c-11e7-8e7f-6d40661ac860.gif)

The only error shown in the console is offscreen-For-WebGL when the skater dips below ground and the pie graph makes non-thermal energy black

**Comment by BryceAG** [comment]
Seems to be chrome specific. Found on windows 10

**Comment by BryceAG** [comment]
Also note how the skater switches direction after the jump. This might be why there is thermal energy if it acts as though the skater moved to get there.

**Comment by brroberts1231** [comment]
@BryceAG has since told me in person that at some point he stopped being able to reproduce this. I am currently trying to reproduce it, but having no luck. If this is something that can't be reproduced, should this issue be closed?

**Comment by samreid** [comment]
@phet-steele can you have a go at reproducing this problem?

**Comment by BryceAG** [comment]
I am able to reproduce it again but I'm still not 100% sure what is causing it. This time she still teleports to the joint but doesn't stay on the track and instead is on the ground. I think it has something to do with dumping thermal energy from the bar graph because it didn't start happening again until I got rid of the thermal energy after the skater came to a complete stop off screen.

**Comment by BryceAG** [comment]
That does seem to be the case. The track has to be on the ground completely flat, and thermal energy must be dumped before clicking 'return skater.' I originally found this while I was investigating how the skater's speed and kinetic energy were always increasing (by an incredibly small amount) in the event log when she was on a flat track. What I didn't notice was that the thermal energy was too, and it was increasing fast enough that you could start to see it on the bar graph. When there is enough thermal energy for the dump button to be clickable is when the skater teleports to the joint.

**Comment by BryceAG** [comment]
This most recent reproduction takes a lot longer (like 5 seconds) for the skater to teleport than the original gif. I'm not sure what I did the first time that made it happen faster or to keep her on the track after the jump. But it is possible that the thermal energy I saw the first time was continuously building like it is in this case, instead of all happening at once during the jump.

**Comment by phet-steele** [comment]
Thanks for your work on this @BryceAG. Turns out this is a variant of #127 and can be reproduced with the procedure in that issue. Going to label this as a duplicate, even though it wasn't obvious.
