### ISSUE TITLE
iPad 2 crashes in mirrors when switching section

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#385]
related to phetsims/QA#50

When testing phet-io mirrors with Tycho, the page would crash and reload whenever I tried to switch sections of the simulation (Intro to Friction, etc.). It would crash right after updating the mirrored sim below, and a bar would pop up on safari stating "A problem occurred with this webpage so it was reloaded."

**Comment by samreid** [comment]
Same problem on iPad3.  Likely we are just over safari's memory limit.  This will not affect clients because they will only be running one instance of the sim at a time on iPad, closing.
