### ISSUE TITLE
iPad 2 instance proxies crashes when launching anything but original state

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#386]
related to phetsims/QA#50

unless you launch from the original state of instance proxies, the launched version will show the loading bar, and once it's full it will crash. Safari will state "A problem occurred with this webpage so it was reloaded." but it won't reload either because the URL is blank.

**Comment by BryceAG** [comment]
by original state, I mean the left window before launching. If you interact with the left window and go into any of the sections this is what will happen, or if you set one of the sections (such as intro) as active.

**Comment by samreid** [comment]
@BryceAG is this still happening in master on phettest?  I didn't see the problem on Mac/Chrome.

**Comment by samreid** [comment]
@lmulhall-phet can you check this on master?

**Comment by lmulhall-phet** [comment]
@samreid, it seems to be fixed on master. I tested on macOS/Chrome/FF/Safari and an iPad 2 running iOS 9.3.5.

**Comment by samreid** [comment]
My thanks!  I need to label this issue as "fixed pending deployment".

**Comment by ariel-phet** [comment]
Handing off to @jessegreenberg to be aware of when he works on deployments

**Comment by jessegreenberg** [comment]
This sounds like the general "out of memory" problem in #435 so I would expect this to have resurfaced for Studio too.

**Comment by jessegreenberg** [comment]
I asked Slack:
```
Jesse Greenberg [10:11 AM]
I have a memory that we discussed in a dev meeting a few weeks ago that PhET-iO Studio didn't need to run in iPad2. Am I off or is that correct? (edited)


Chris Klusendorf [10:12 AM]
That’s what I remember as well.

Sam Reid [10:13 AM]
Studio doesn’t need to run on iPads (any generation) for now. (edited)

Ariel Paul [10:14 AM]
And definitely not on iPad2

Jesse Greenberg [10:14 AM]
OK thanks
```

So this issue can be closed since Studio is not supported on that platform.
