### ISSUE TITLE
Why are we using GaugeNeedleNode?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park-basics#387]
@samreid looks like ESPB is using both of these:

`GaugeNeedleNode`
`GaugeNode`

`GaugeNeedleNode` is just a needle, while `GaugeNode` is the entire gauge (_needle_, text, value, etc..). Since both of these are being used and both are tandemized, we get two needle entries in instance-proxies:

(1) `energySkateParkBasics.introScreen.view.gaugeNeedleNode` (the `GaugeNeedleNode` needle)

(2) `energySkateParkBasics.introScreen.view.speedometerNode.needle` (the `GaugeNode`needle)

(1) is what is actually being presented in the sim, while (2) has the needle hidden by setting its property to null in `EnergySkateParkBasicsScreenView` line 222:

```js
 var speedometerNode = new GaugeNode(
      // Hide the needle in for the background of the GaugeNode
      new Property( null ), propertiesSpeedString,
      {
        min: 0,
        max: 20
      }, ...
```

This seems pretty unconventional, and maybe is a product of this sim's age. It does significantly complicate ESPB's API though, since you can enable both and get quite confused:

<img width="562" alt="screen shot 2017-10-02 at 3 22 40 pm" src="https://user-images.githubusercontent.com/5863899/31100138-9753c70a-a785-11e7-8960-418569eaa786.png">

I went ahead and tested completely removing the usage of `GaugeNeedleNode` and enabling the needle property in `GaugeNode` instead of setting it to null. Everything worked just fine after that. @samreid why don't we do this instead? It would remove this "duplicate" entry.

For phetsims/QA/issues/50. Thanks @BryceAG for finding this and @jessegreenberg for testing some code changes.
I typed "needle" 16 times in this issue. It doesn't look like a word anymore.

**Comment by samreid** [comment]
The built-in gauge needle is suppressed and another needle drawn in webgl is overlayed so that everything that animates is in webgl and in the same layer to attain smooth performance on slow platforms.  There is no straightforward way to uninstrument the hidden one and I'm hesitant to reduce performance by eliminating the webgl one.  However, I am trying to picture an eventual PhET-iO design meeting for this sim.  It is difficult for me to imagine someone wanting to keep the speedometer but not the needle node, so perhaps this is an indication we should uninstrument the needles.

**Comment by samreid** [comment]
Needles are uninstrumented and no longer appear in instance proxies.  @phet-steele anything else to discuss for this issue?

**Comment by phet-steele** [comment]
I suppose this is one way to handle it! I do not think there is anything left to discuss. @samreid please have this verified by QA in the next testing cycle.

**Comment by samreid** [comment]
On hold until next RC

**Comment by jessegreenberg** [comment]
Closing, this no longer applies, a separate GaugeNeedleNode is not being used anymore since WebGL was removed from sim.
