### ISSUE TITLE
Skater falls through track

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/energy-skate-park-basics#388]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6

**Browser:**

Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Problem description:**

I know there have been 80,000 similar issues, but I thought I'd make this one for posterity. If anyone in the future is reading this, hopefully you'll understand why this issue was deferred! (Or maybe we can find a solution.) This is for phetsims/QA/issues/50.

The skater falls through the track unexpectedly. See the gif below.

**Steps to reproduce:**

1. Select the Playground screen.
2. Create a similar setup to the one in the gif. (Make sure you click the non-stick-to-track button.)
2. Experiment with the drop point of the skater.
3. Eventually, you'll find a drop point that makes the skater fall through the track.

**Screenshots:**

![oct-06-2017 13-44-51](https://user-images.githubusercontent.com/31285590/31295649-9612c8d6-aa9c-11e7-806b-f8b38c551eaf.gif)

URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.4.0-phetiorc.1/energy-skate-park-basics_en-phetio.html?phetioStandalone

**Comment by samreid** [comment]
I am guessing that this problem occurred because in one time step the skater traversed both the track and the ground, and the logic for the ground took precedence.  I'll leave it to @ariel-phet whether he wants an investigation.

**Comment by ariel-phet** [comment]
@samreid no investigation necessary. I don't personally see this as pedagogically problematic. Since the "drop through" point is coinciding with the ground. Especially since there is no expectation of "sticking to the track".

As such, @lmulhall-phet I do not think I would actually even consider this a bug, it strikes me as normal and reasonable behavior.
