### ISSUE TITLE
Instance Proxies sliders bounds are not set right

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#389]
There are many sliders in instance proxies with the default range from 0 to 1, but actually go beyond those bounds. 

Screen Index Property: which section of the sim is highlighted in the home screen. Currently from 0 to 1, but actual values are 0, 1, and 2. For this one it might also be good to set it so only integers can be chosen, because any decimal point makes it so none are selected. Additionally, when messed with and not on the home screen, it will have the bounds .01 and .89, and the screen other than the nav bar will be black.

Parametric Speed Property: how fast the skater is moving with left being negative and right positive. Currently from 0 to 1, but values can be negative and magnitude much larger than one.

Mass Property: when dragged it is from 0 to one, but even the default (62.5) is out of bounds, and the max is 100

Kinetic Energy Property: From 0 to 1, but the actual values are often seen in the hundreds or higher.

Potential Energy Property: From 0 to 1, but the actual values are often seen in the hundreds or higher.

Thermal Energy Property: From 0 to 1, but the actual values are often seen in the hundreds or higher.

Total Energy Property: From 0 to 1, but the actual values are often seen in the hundreds or higher.

Angle Property: From 0 to 1, which corresponds to straight up or 45 degrees to the right. Actual values can be negative and/or magnitude greater than one

Scene Property: Which track is show for the section. From 0 to 1, but actual values are 0, 1, and 2. For this one it might also be good to set it so only integers can be chosen, because any decimal point makes it so none are selected.

Friction Property: From 0 to 1, but only 0 to .1 is currently used on the bar in sim. When set to 1, the skater will stop before being at the bottom of the parabola track, and will switch directions frequently despite having no speed or change in position.

These are true for all sections (intro, Friction, and Lab).

**Comment by BryceAG** [comment]
related to phetsims/QA#50

**Comment by samreid** [comment]
Proposed fix is in the preceding commit, @BryceAG can you please review on phettest?

**Comment by phet-steele** [comment]
Screen Index Property: uses integer radio buttons 👍

Parametric Speed Property: read only 👍

Mass Property: slider ranges from 25 - 100 kg and matches the sim's sliders 👍

Kinetic Energy Property: read only 👍

Potential Energy Property: read only 👍

Thermal Energy Property: read only 👍

Total Energy Property: read only 👍

Angle Property: read only 👍

Scene Property: uses integer radio buttons 👍

Friction Property: slider ranges from 0 to 0.1 units and matches the sim's sliders 👍

All sliders identified in this issue are correct. Thanks, @samreid.
