### ISSUE TITLE
Events: Firefox poor performance

### ISSUE THREAD

**Issue by BryceAG** [phetsims/energy-skate-park-basics#391]
Related to phetsims/QA#50

All of the phet-io events: sections have poor performance for Windows 10 Firefox. In order of decreasing severity: JSON, colorized, and text area. With the first 2 there was a lot of input delay, often temporarily setting Firefox in a (Not Responding) state, and with all of them the skater moved noticeably slower than usual and dragging objects had poor frame rate. For JSON the skater appeared to move just as fast for normal speed and slow motion speed. When events were no longer being recorded (by cutting a track as in #380) performance became normal.

**Comment by samreid** [comment]
The simulation is emitting nearly 1500 messages per second, which is 25 messages per frame.  This is due to the skater, speed, position, angle, energy, etc changing in every frame.  @zepumph will this be a problem for metacog?  What should we do?

**Comment by samreid** [comment]
Firefox quantum is out today, but we still need to answer what can/should we do about such a dense data stream.  Unassigning until discussion with @zepumph

**Comment by ariel-phet** [comment]
Should be retested with latest firefox.

**Comment by zepumph** [comment]
I don't think I'm totally qualified to call myself a tester, but I found that on the build version from master, in the JSON Events wrapper, it was not laggy on the newest version of firefox quantum. I will say that it was very laggy with the console out, but that is due more towards all of the printing of events to the console that was happening (not sure if that is the same issue).

Taking off hold. @samreid let's talk about this if it is still an issue.

**Comment by samreid** [comment]
I suspect that in the PhET-iO redesign the data stream will be sparser and it will have better performance.  @ariel-phet what do you think about requesting @BryceAG to test on latest firefox, to rule that out as a variable?

**Comment by ariel-phet** [comment]
@samreid I agree that would be good. Latest FF has made big strides in performance.

**Comment by ariel-phet** [comment]
@BryceAG or someone else from QA at @phet-steele discretion, it would be good to look at this performance on latest firefox.

**Comment by lmulhall-phet** [comment]
@samreid, here's what colorized looks like on macOS:

![espb](https://user-images.githubusercontent.com/31285590/40868799-fa4e05a8-65cd-11e8-91b4-1f133f20e8bc.gif)

I think it's safe to say that FF Quantum didn't solve this issue. I'll do some further testing on a Windows machine.

**Comment by ariel-phet** [comment]
@lmulhall-phet or @KatieWoe can you do further testing on a windows machine?

**Comment by KatieWoe** [comment]
Just tested colorized on Windows 10 Firefox and there does not seem to be an improvement.
At first the sim runs ok, with a bit of lag behind the mouse, similar to what @lmulhall-phet demonstrated.  However, after about a minute of running the sim is no longer able to be interacted with and starts putting up a not responding error.  The console stops showing new entries and this error is displayed.

![crash](https://user-images.githubusercontent.com/41024075/43906959-b5a93a3e-9bb1-11e8-9058-0e73e5576c1e.PNG)

This is the sim before it starts crashing.

![perform](https://user-images.githubusercontent.com/41024075/43907009-caccee74-9bb1-11e8-84b7-2da25d7bd293.gif)

**Comment by samreid** [comment]
On Mac Firefox on my laptop , performance drags when the console is getting full (5fps dragging the skater), then improves when clearing the console (back to 60fps or so).  Perhaps we can rely on developers knowing when buffers are getting full?

Regarding making the messages sparser, dragging the skater creates a message like this:
```
72122 energySkateParkBasics.playgroundScreen.view.skaterNode.inputListener dragged {"x":449,"y":289}
	72123 energySkateParkBasics.playgroundScreen.model.skater.positionProperty changed {"oldValue":{"x":-2.0954773869346726,"y":6.881501256281407},"newValue":{"x":-2.0675376884422105,"y":6.867531407035176}}
	72124 energySkateParkBasics.playgroundScreen.model.skater.potentialEnergyProperty changed {"oldValue":4214.9195194723625,"newValue":4206.362986809046}
	72125 energySkateParkBasics.playgroundScreen.model.skater.totalEnergyProperty changed {"oldValue":4214.9195194723625,"newValue":4206.362986809046} 
```

It doesn't seem like we would be able to make that any more sparse.

@zepumph what do you think about this problem?

**Comment by zepumph** [comment]
To me this seems like an understandable problem since there is so much data. I didn't see this problem when the console was closed (correct me if I'm wrong). I would recommend a note in the wrapper index for these links saying that performance can be effected by such verbose logging to the console. 

It shouldn't effect the normal use case, which is piping that data elsewhere (not the console), but we should verify that. 

If it really is only in the console and it needs to be solved, we could explore using `console.clear()` for certain cases we detect where we think it will be less performant.

**Comment by samreid** [comment]
It's my instinct that we will need to trust our clients to understand when the console or a textbox is getting too full.  If we have one or more clients that struggle with this, then we should re-evaluate.  @zepumph OK to close for now?
