### ISSUE TITLE
lastDragPoint duplicated in TrackDragHandler and SimpleDragHandler

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#413]
Noticed while working on https://github.com/phetsims/scenery/issues/804.

TrackDragHandler and its supertype SimpleDragHandler both have field `this.lastDragPoint`.   Since `this.lastDragPoint = null` is set in TrackDragHandler before SimpleDragHandler.call, I suspect that either @samreid was unaware of this, or `lastDragPoint ` was added to SimpleDragHandler at a later time. Either way this is not good.  SimpleDragHandler `lastDragPoint` is likely private (no other clients use it), but see https://github.com/phetsims/scenery/issues/804.

**Comment by jessegreenberg** [comment]
I will look into this as part of https://github.com/phetsims/energy-skate-park-basics/issues/375.

**Comment by pixelzoom** [comment]
I believe the supertype field should be `@private`, but check with @jonathanolson and phetsims/scenery#804.   And if the intention is to set the supertype field, that needs to be done _after_ calling the supertype constructor, and it's highly likely to conflict with the assignment done in SimpleDragHandler.move, so not recommended.

**Comment by jonathanolson** [comment]
> I believe the supertype field should be @private, but check with @jonathanolson and phetsims/scenery#804

Yes it should probably be private. If some hacking was needed to make things work properly, maybe other changes are needed.

**Comment by jessegreenberg** [comment]
Before TrackDragHandler was created, `lastDragPoint` was in TrackNode and was not an instance variable. Seen here: https://github.com/phetsims/energy-skate-park-basics/blob/3c7d303cc672f13523f31b94c60372ce31d962c9/js/view/TrackNode.js. So it is unlikely that TrackDragHandler is doing something hacky to modify SimpleDraghandler's `lastDragPoint`.

Inspecting repo at that SHA, I still only see 2 hits for `lastDragPoint`
```js
   44      if ( track.interactive ) {
   45:       var lastDragPoint;
   46        var startOffset = null;
   47  
   ..
   66            //On the first drag event, move the track out of the toolbox, see #205
   67            if ( !startedDrag ) {
   68:             lastDragPoint = event.pointer.point;
   69              track.dragging = true;
```

So it doesn't look like it was really doing anything then either. Im going to remove it.

**Comment by jessegreenberg** [comment]
I removed it and tested track dragging, everything seemed OK. @samreid does this look OK to you?

**Comment by samreid** [comment]
I reviewed this code change and tested dragging tracks on the third screen and did not see any issues.  Thanks for pointing out this collision @pixelzoom.  Back to you @jessegreenberg, close if there's nothing else to do.

**Comment by jessegreenberg** [comment]
OK, thanks @samreid .
