### ISSUE TITLE
Can't drag tracks after dragging control point if track snaps above ground

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park-basics#414]
From #205 @samreid found

>  I'm also seeing a bug where if you tap (not drag) a track from the toolbox, then drag any of its control points, the track can no longer be dragged by the gray part. I do not know if that bug was caused by these changes or is a new issue.

It does not seem related to #205 so making a new issue to track down.

**Comment by jessegreenberg** [comment]
Oh wait, we are probably going to make it so the track can't snap out of the toolbox on click, this could be a non-issue if t is not possible to get sim into this state.

**Comment by jessegreenberg** [comment]
Tracks only snap out of toolbox after drag again, but this is still a problem. Steps to reproduce:
- Drag trackout of toolbox, release below ground so it snaps above ground
- Drag a control point so that the track repositions itself above ground

Track is not draggable anymore.

**Comment by jessegreenberg** [comment]
It is from this case:

```js
        if ( track.dragSource === self ) {
          self.trackDragged( event );
        }
```
dragSource is defined but not equal to self in this case.

**Comment by jessegreenberg** [comment]
Ah - For the record, this bug is in the published version.

**Comment by samreid** [comment]
> I was able to reproduce this bug in the published version.

Good to know, thanks for checking that!

**Comment by jessegreenberg** [comment]
It looks like `Track.physicalProperty` is not being set to true when it is bumped above ground.

Currently, the track isn't made physical when it is bumped above ground, and so when dragging starts on the ControlPointNode, the `track.dragSource` is set to the ControlPointNode's simple drag handler.

```js
        // If control point dragged out of the control panel, translate the entire track, see #130
        if ( !track.physicalProperty.value || !track.droppedProperty.value ) {

          // Only start a track drag if nothing else was dragging the track (which caused a flicker), see #282
          if ( track.dragSource === null ) {
            track.dragSource = inputListener;
          ...
```
But then on ControlPointNode `drag`, the track is made physical, because `trackDragged` is called while the track is above ground. Finally, since the track has been made physical, we never call in trackDragHandler.trackDragEnded to clear `track.dragSource` in ControlPointNode drag `end.`

**Comment by jessegreenberg** [comment]
That seems to have fixed it.  Closing this issue.
