### ISSUE TITLE
Dispose Thermal Energy button appears clickable when it is not

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/energy-skate-park-basics#416]
Test device: PC Laptop

Operating System: All versions

Browser: All

Problem description: When the dispose thermal energy button associated with the pie chart is grayed out, indicating that it can't be clicked on, and a user scrolls over the button the cursor changes to a finger which it should not. All other buttons that aren't clickable, including the other dispose thermal energy button associated with the bar graph, do not exhibit this same behavior.

Screenshots:
![espb_energy_button](https://user-images.githubusercontent.com/30352536/42063155-a15eda32-7aed-11e8-9818-0cfe2e316672.gif)

<details>
<summary>
Troubleshooting Info:
</summary>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by jessegreenberg** [comment]
Hmm, weird this isn't an issue doesn't happen for the other ClearThermalButton in the bar graph.

**Comment by jessegreenberg** [comment]
This is not an issue for the deployed version of the sim.

**Comment by jessegreenberg** [comment]
Ah, PieChartLegend has cursor: 'pointer', and when disabled, RectangularButtonViews have cursor "null", so they inherit from their parent.

Is there a reason why the panel has a `pointer` cursor?

**Comment by jessegreenberg** [comment]
Hmm, after  checking out SHAs for 1.1, I would have expected this bug to be in the published version as well, I don't see any notable differences. But this is the only clickable item in the panel so I believe it is safe to remove the cursor option from the panel.

**Comment by jessegreenberg** [comment]
Since we are currently in dev testing, we can be sure that the fix will make it into an upcomming RC. Closing this issue.
