### ISSUE TITLE
Kink/Loop in track after making a connection

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#420]
**Test Device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome
**Problem description:**
When connecting two pieces of track one of the points will shift and cause a kink or loop in the track, instead of a smooth curve.
For phetsims/QA/issues/134
**Steps to reproduce:**
1. Go to the playground screen
2. Manipulate the first piece of track so that it is a sharp bowl shape opening to the left.
3. Select a new piece of track and place it to the left of the bottom piece of the existing track but do not connect them yet
4. Drag the middle point of the new track down to form a gentle curve
5. Connect the two pieces of track
**Screenshots:**
![kink in energy skate park basics](https://user-images.githubusercontent.com/41024075/42541817-3dfd1f3a-8461-11e8-9918-54e22843d631.gif)

Troubleshooting information (do not edit):
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1536x741
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by jessegreenberg** [comment]
Thanks  for reporting @KatieWoe. @ariel-phet is this a bug, and if so does it need to be fixed for the LoL/phetio release?

**Comment by jessegreenberg** [comment]
I don't think this is a bug personally, just the behavior of the cubic splines.

**Comment by ariel-phet** [comment]
@KatieWoe @jessegreenberg I also do not think this is a bug, especially since it does not create a super sharp kink. I think this can be closed.
