### ISSUE TITLE
Increasing Thermal and Total Energy When Shaking Track

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#422]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome 67.0.3396.99
**Problem description:**
For phetsims/QA/issues/134
Possibly related to phetsims/energy-skate-park-basics/issues/32 and phetsims/energy-skate-park-basics/issues/418
When shaking the track in the playground screen while the skater is moving, thermal energy can continuously go up, making thermal energy and total energy in the bar and pie charts very large.
**Steps to reproduce:**
1. Go to the play ground screen
2. Select a piece of track and shape it so that it forms a bowl shape
3. Move the thumb on the friction slider to "lots"
4. Release the skater so that she moves back and forth on the track
5. Grab the track and quickly move it up and down.  Thermal and total energy will increase.  This only happens so long as the skater is moving back and forth on the track.
**Screenshots:**
![increasing energy by shaking](https://user-images.githubusercontent.com/41024075/42588288-a1e29f22-84fa-11e8-9455-4a6b277b054a.PNG)

Troubleshooting information (do not edit):
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1536x741
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by jessegreenberg** [comment]
Here is a recording of this behavior:
<a href="https://gyazo.com/1fe3320aa5049126676a439939ffdf2b"><img src="https://i.gyazo.com/1fe3320aa5049126676a439939ffdf2b.gif" alt="Image from Gyazo" width="2000"/></a>

@arouinfar @ariel-phet can you please help determine what the correct behavior would be for this case?

**Comment by ariel-phet** [comment]
@KatieWoe @jessegreenberg @arouinfar 

I don't think this is actually a bug. You are vigorously shaking the track, the skater is moving on the track (as seen in the video) so you are continuing to add thermal energy to the system. 

@KatieWoe thanks for pointing this out, but I think the behavior is reasonable for the situation (since total energy does continue to increase). I also think any attempts at a different behavior would be problematic and complicated. 

Closing
