### ISSUE TITLE
Switching Between normal and full screen moves track out of bounds

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/energy-skate-park-basics#427]
**Test Device:**
Mac Laptop
**Operating System:**
MacOS Sierra v. 10.12
**Browser:**
All
**Problem Description:**
When a track has been created and it touches the edges of the screen bounds in the normal view switching to full screen moves the track ends out of bounds. The screen shots below exemplify this, with the first one being the normal view and the second one the same track but the simulation has been switched to full screen mode.
![screen shot 2018-07-13 at 1 41 12 pm](https://user-images.githubusercontent.com/30352536/42710818-dc804202-86a2-11e8-87ac-9a0664b1d107.png)
![screen shot 2018-07-13 at 1 29 23 pm](https://user-images.githubusercontent.com/30352536/42710826-e177dd06-86a2-11e8-900a-258cc2f8f786.png)

**Comment by jessegreenberg** [comment]
@JRomero0613 which version did you encounter this, 1.4.0-dev.1 or master? I expect this to be fixed in master by changes for https://github.com/phetsims/energy-skate-park-basics/issues/417.

**Comment by JRomero0613** [comment]
@jessegreenberg This bug was present in version 1.4.0-dev.1, and not in master. If this is what you wanted then I say we can go ahead and close this issue.

**Comment by jessegreenberg** [comment]
Great, thanks for checking @JRomero0613. In that case I think we can close this issue since it is fixed and won't show up in the next version.
