### ISSUE TITLE
Strange Multitouch Behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#429]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome 67.0.3396.99
**Problem description:**
The skater will randomly teleport, gain energy, and fly off in random directions if held aloft while switching tracks in the intro and friction screens.  This is done using multitouch.
For phetsims/QA/issues/134
**Steps to reproduce:**
1. Go to the intro screen.
2. Drag the skater to an empty part of the screen and Fire on Hold
3. While holding the skater, select one of the other track scene buttons using multitouch.
4. To see effect on energy, select the Bar Graph checkbox

**Screenshots:**
Since you can't see what my hands are doing.  My left hand is holding the skater in one place, not moving.  My right is selecting different scene buttons or activating the bar graph.
![strange](https://user-images.githubusercontent.com/41024075/42895461-3cb30f92-8a77-11e8-923a-02a4402e04fc.gif)

Troubleshooting information (do not edit):
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1536x741
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by KatieWoe** [comment]
Issue is also present on iOS 9.3.5 on the iPad Air 2.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, reproduced.

**Comment by jessegreenberg** [comment]
I was able to reproduce the issue in the published sim, just checked to see if it was related to #371

**Comment by jessegreenberg** [comment]
When switching scenes, the skater is supposed to reset but maybe the drag handler is not interrupted.

**Comment by jessegreenberg** [comment]
Fixed in the above commit. Closing.
