### ISSUE TITLE
Report on how much time to take care of PhET-iO part, for QA and dev side

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#438]
From my meeting notes from several weeks ago:

> It would be good to understand how much time it takes to do the phet-io part for ESPB, from QA side and dev side.

Self-assigned to identify and report as possible.

**Comment by samreid** [comment]
I have not been in tune with this work.  I'm seeing that https://github.com/phetsims/energy-skate-park-basics/issues/411 requested a new RC in March 2018, and phet-io has been in a lot of churn since then.   Several issues came out of RC testing, listed in https://github.com/phetsims/QA/issues/134.  @jessegreenberg can you please chime in about the status of this redeploy?

**Comment by samreid** [comment]
As noted in https://github.com/phetsims/energy-skate-park-basics/issues/411#issuecomment-443373651

> At Thursday's meeting @kathy-phet recommended to put this re-release on hold. The PhET-iO ESP/ESPB will require more work and deliberation before we continue.

@jessegreenberg reported on the status of the redeploy--if I recall correctly, it had been through one round of dev or rc testing, and most or all discovered issues were repaired.  Leaving assigned to @jessegreenberg to clarify.

**Comment by arouinfar** [comment]
This issue is related to a release that never happened, so I'm going to close it.
