### ISSUE TITLE
Erase button can freeze sim

### ISSUE THREAD

**Issue by rea-laura** [phetsims/energy-skate-park-basics#450]
<b>Test Device</b> 

Jordan

<b>Operating System</b>

Mojave 10.14.2

<b>Browser</b>

Chrome 71.0.3578.98

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/226:
When thermal energy is discarded, erasing the track can cause the sim to freeze. Could be related to https://github.com/phetsims/energy-skate-park-basics/issues/449.

<b>Steps to Reproduce</b>

1) open energy skate park basics from phettest.colorado.edu.
2) select "playground" from home menu
3) turn on bar graph and pie graph
4) build a simple parabola with its vertex touching the bottom
5) start skater on track and let them oscillate until all the energy has been converted into thermal _and_ the pie graph above them changes to a dashed yellow circle.
![screen shot 2018-12-18 at 11 24 50 am](https://user-images.githubusercontent.com/44005544/50174507-9d218080-02b7-11e9-9d8e-ae45bb6cb6d7.png)
6) discard the thermal energy using the trash can. Note there is still a small amount of total energy left in the bar graph
![screen shot 2018-12-18 at 11 25 03 am](https://user-images.githubusercontent.com/44005544/50174516-a27ecb00-02b7-11e9-8cf8-aab419a43b34.png)
7) press the erase button. This will freeze all of the sim, except for the reset button and the home menu bar at the bottom. Sometimes the problem resolves itself, other times pressing the reset button will fix it.

**Comment by samreid** [comment]
Thanks @rea-laura, I'm also assigning @jessegreenberg so he's aware of it and in case he addresses it before I get here.

**Comment by samreid** [comment]
@jessegreenberg can you reproduce this problem?  If so, would you like to investigate, or should I take a look?

**Comment by jessegreenberg** [comment]
This is no longer an issue, I am not able to reproduce following the steps above. In addition, the dashed "total energy" pie chart doesn't appear anymore in basics version.
