### ISSUE TITLE
instance metadata should match for energySkatePark.measureScreen.measureScreenView.controlPanel

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#453]
Similar to #452 I also saw:

> instance metadata should match for energySkatePark.measureScreen.measureScreenView.controlPanel

But I didn't see this problem locally, not sure why.  @zepumph can you please take a look?

**Comment by zepumph** [comment]
I'm thinking that this issue is too stale to be worked on. Closing
