### ISSUE TITLE
White space in bar graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#454]
The bar graph was altered for ESP to allow more room for negative bars.  This has altered ESPB.  This is undesired because ESPB will not have negative bars during normal use.
![bargraph](https://user-images.githubusercontent.com/41024075/50927873-4b7f9800-1416-11e9-80bd-107adfcee84c.PNG)

**Comment by jessegreenberg** [comment]
Fixed with the above commit, removed negative space if graph doesn't allow for negative values.
