### ISSUE TITLE
Chromium slow down on published sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#467]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome (and Edge)
**Problem description**
On the published sim, the speed of the skater when falling and moving on the track is very slow. It is to the point that it is hard to tell the difference between normal and slow motion settings. Firefox may have a bit of slow down, but not as much.

**Visuals**
![sloweddownskater](https://user-images.githubusercontent.com/41024075/73874346-97b32c80-4810-11ea-8b07-d2db8bee692c.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park: Basics‬
URL: https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html?profiler
Version: 1.1.19 2020-01-04 13:55:38 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"722f1732","branch":"master"},"brand":{"sha":"b2c18993","branch":"HEAD"},"chipper":{"sha":"3676ff96","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"energy-skate-park-basics":{"sha":"c39248e6","branch":"HEAD"},"joist":{"sha":"8f1daa58","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"8dcefdcd","branch":"HEAD"},"phetcommon":{"sha":"e31285e4","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"6e2ab45b","branch":"HEAD"},"scenery-phet":{"sha":"c4caf4df","branch":"HEAD"},"sherpa":{"sha":"2b2bdfd9","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
https://github.com/phetsims/QA/issues/470 doesn't seem to have this at first glance

**Comment by jessegreenberg** [comment]
OK thanks @KatieWoe, good to hear that sim is faster off of master. Many changes to rendering have been introduced since last publication. We will know more about performance of master on our slower devices through https://github.com/phetsims/QA/issues/470, closing this issue.
