### ISSUE TITLE
Move Energy Bar Graph to AccordionBox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park-basics#477]
Related to #473 

Discussed in the 6/23/22 design meeting.

In effort to unify the designs of ESP and ESPB, we decided to use the Bar Graph AccordionBox in the Basics version. The look and behavior will be identical to ESP.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/8419308/175427563-bfddb0af-8dda-4840-9cb2-87257a0359c5.png">

**Comment by jessegreenberg** [comment]
Done in the above commits @arouinfar. Note this added zoom buttons to the graph in basics, which were previously not available.

**Comment by jessegreenberg** [comment]
The "Bar Graph" checkbox and the option to display it has been removed entirely from the code because they are no longer used.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg, looks good in master.
