### ISSUE TITLE
What are the 1.4 and 1.4-phetio release branches?

### ISSUE THREAD

**Issue by zepumph** [phetsims/energy-skate-park-basics#478]
While working on https://github.com/phetsims/perennial/issues/318, I saw that the MR process found ESPB 1.4 as an unreleased branch. On master it looks like the package is still at 1.4, and it seems that @jonathanolson has been maintenance releasing this branch for years. 

The first commit is from 2017, so likely this is a ditched branch, and we should ignore it. 

https://github.com/phetsims/energy-skate-park-basics/commit/5754f294d1ee8d2fb914444dbf7b45134e0b7983

@samreid can we do these steps:
- [ ] delete the 1.4-phetio branch?
- [ ] delete the 1.4 branch?
- [x] mark ESPB on master at 1.5? 
- [x] mark 1.4 as `ignoreForAutomatedMaintenanceReleases`, or delete it. one or the other.

**Comment by samreid** [comment]
That sounds correct to me, but let's double check with @jessegreenberg who has been listed as responsible-dev for this repo since at least 2018.

**Comment by arouinfar** [comment]
These issues may shed some light on the 1.4 branch:
https://github.com/phetsims/energy-skate-park-basics/issues/411
https://github.com/phetsims/energy-skate-park-basics/issues/464
https://github.com/phetsims/energy-skate-park-basics/issues/375

**Comment by zepumph** [comment]
Thanks! Looks like the most important thing is when we decided to put that release "on hold" on my birthday 5 years ago (!!) https://github.com/phetsims/energy-skate-park-basics/issues/411#issuecomment-443373651.

With that in mind, @jessegreenberg and @samreid I think we should bump master up to 1.5 and leave the 1.4 branches to wither in perpetuity without release. In https://github.com/phetsims/energy-skate-park-basics/commit/6de71e1045ce8f35e08e56a2a90a0f1faf7df58e we are no longer implicating 1.4 in MRs (yay), and 1.4-phetio will never be touched again.

Happy to delete them also, but that isn't really PHET's style. 

@jessegreenberg, would you please take a look and feel free to close or delete the branches. Whatever you'd like.

**Comment by jessegreenberg** [comment]
Great, thanks. I also found https://github.com/phetsims/energy-skate-park-basics/issues/379 for history, it is the issue referenced in the 1.4 branch creation.

Leaving the branches makes sense to me, and I am happy to hear they will not cause more maintenance trouble after https://github.com/phetsims/energy-skate-park-basics/commit/6de71e1045ce8f35e08e56a2a90a0f1faf7df58e.
