### ISSUE TITLE
CT: preferencesModel.skaterCharacterSetProperty.link is not a function

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park-basics#479]
![image](https://github.com/phetsims/energy-skate-park-basics/assets/679486/55f03934-77a5-46f1-afef-eb62bdf03ce7)

**Comment by samreid** [comment]
It thinks skaterCharacterSetProperty is a Tandem.

**Comment by jessegreenberg** [comment]
Thanks! Fixed in the above commit, and I think related to https://github.com/phetsims/center-and-variability/issues/531. Closing.

**Comment by samreid** [comment]
Thanks @jessegreenberg!
